/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eaedff",
        "inverse-primary": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "outline": "#777587",
        "on-background": "#131b2e",
        "primary-fixed-dim": "#c3c0ff",
        "surface": "#faf8ff",
        "brand-purple-glow": "#9855FF",
        "secondary-container": "#8a4cfc",
        "on-tertiary-fixed-variant": "#005236",
        "brand-purple-light": "#C49BFF",
        "surface-container-high": "#e2e7ff",
        "tertiary-container": "#006e4b",
        "brand-violet": "#7C3AED",
        "error-container": "#ffdad6",
        "primary": "#3525cd",
        "inverse-on-surface": "#eef0ff",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#faf8ff",
        "text-primary": "#0F172A",
        "secondary-fixed": "#eaddff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#4d44e3",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-low": "#f2f3ff",
        "surface-variant": "#dae2fd",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#002113",
        "status-rose": "#F43F5E",
        "status-emerald": "#10B981",
        "tertiary-fixed-dim": "#4edea3",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#d2bbff",
        "border-subtle": "#E2E8F0",
        "outline-variant": "#c7c4d8",
        "text-secondary": "#64748B",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-card": "#FFFFFF",
        "surface-card-subtle": "#F1F5F9",
        "on-primary-container": "#dad7ff",
        "text-muted": "#94A3B8",
        "primary-container": "#4f46e5",
        "brand-indigo": "#4F46E5",
        "surface-container-highest": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "canvas-bg": "#F8FAFC",
        "background": "#faf8ff",
        "status-amber": "#F59E0B",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-secondary-fixed": "#25005a",
        "on-surface-variant": "#464555",
        "secondary": "#712ae2",
        "tertiary": "#005338",
        "border-hover": "#CBD5E1",
        "on-error": "#ffffff",
        "on-surface": "#131b2e",
        "inverse-surface": "#283044",
        "surface-dim": "#d2d9f4",
        "on-tertiary-container": "#67f4b7",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Outfit", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-hero": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["52px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
