spring:
  application:
    name: snaplink-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

# Redis cấu hình tham chiếu biến môi trường
# spring:
#   data:
#     redis:
#       host: ${REDIS_HOST:localhost}
#       port: ${REDIS_PORT:6379}

app:
  jwt:
    secret: ${JWT_SECRET:your_super_secret_key_at_least_256_bits_long_default_snaplink_secret}
    expiration-ms: ${JWT_EXPIRATION:86400000}

